-- MySQL Script generated by MySQL Workbench
-- Tue Mar 18 15:07:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema users_data
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema users_data
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `users_data` DEFAULT CHARACTER SET utf8mb3 ;
USE `users_data` ;

-- -----------------------------------------------------
-- Table `users_data`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_data`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `nickname` VARCHAR(20) NOT NULL,
  `userId` VARCHAR(10) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `email` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickname` (`nickname` ASC) VISIBLE,
  UNIQUE INDEX `userId` (`userId` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `users_data`.`tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users_data`.`tasks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(20) NOT NULL,
  `memo` TEXT NULL DEFAULT NULL,
  `userId` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `tasks_ibfk_1`
    FOREIGN KEY (`userId`)
    REFERENCES `users_data`.`users` (`userId`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
