CREATE TABLE users(
    id INT(10) NOT NULL AUTO_INCREMENT,
    username VARCHAR(20) NOT NULL,
    nickname VARCHAR(20) UNIQUE NOT NULL,
    userId VARCHAR(10) UNIQUE NOT NULL,
    password VARCHAR(10) NOT NULL,
    email VARCHAR(35) UNIQUE NOT NULL,
    CONSTRAINT users_PK PRIMARY KEY(id)
);